### ISSUE TITLE
Lora & parameters freezing

### ISSUE THREAD

**Issue by Evan-Yun-love** [zongzi13545329/SimAda#1]
你好，我在看代码过程中遇到一些问题想要请教一下。第一个问题是关于lora的模型，我看image_encoder_lora.py里定义了_LoRA_qkv类，在Block类里初始化了这个类，但是在Block的前向过程forward里并没有使用到Lora，那么LoRA的作用体现在哪呢？这是第一个疑问。第二个疑问是关于参数冻结，按照论文的说法，image_encoder除了adpter外的其他参数会冻结，实现这部分功能的代码我在train.py和function.py里没有找到，能否说明一下是怎么实现的（也许是我阅读还不够仔细）？还请不吝赐教

**Comment by zongzi13545329** [comment]
感谢你的提问，这是因为代码上传失误导致的。因为论文目前正在under review，且增加了额外的设计更新，因此我会在结果出来后再update debug后的代码。
以及补充关于你提出问题的解答：1._LoRA_qkv类取代了原始attention里的qkv矩阵，在前向forward里进行传播（和正常更行原始qkv一样）2.参数冻结部分在function.py里实现。具体来说，在function.py的130行位置插入：
            for n, value in net.image_encoder.named_parameters():
                if "Adapter" not in n :
                    if "linear_" not in n :
                        value.requires_grad = False
希望这能解答你的疑惑。

**Comment by Evan-Yun-love** [comment]
已收到您的邮件，谢谢

**Comment by Evan-Yun-love** [comment]
谢谢你的解答，我已明白！
